version: "3.9"

services:
  api:
    build: ./api
    volumes:
      - ./api/src:/usr/app/src
    environment:
      - PORT
      - POSTGRES_CONNECTION:
      - POSTGRES_USER:
      - POSTGRES_PASSWORD:
      - POSTGRESS_DB: db

    ports:
    - "3000:3000"

    depends_on:
    - pg


    pg:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

